# Generated by Django 3.1.6 on 2021-02-27 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_moderator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=100)),
                ('stage_place', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Muzicki', 'Muzicki'), ('Filmski', 'Filmski'), ('Likovni', 'Likovni'), ('Plesni', 'Plesni'), ('Kulinarski', 'Kulinarski')], default='Muzicki', max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
                ('event_img', models.URLField(default='#')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.stage')),
            ],
        ),
    ]
