# Generated by Django 3.1.6 on 2021-03-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_event_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.CharField(choices=[('1', 'Petak'), ('2', 'Subota'), ('3', 'Nedjelja')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.TimeField(),
        ),
    ]
