# Generated by Django 3.1.6 on 2021-03-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210303_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_date',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_date',
            new_name='start_time',
        ),
    ]
