# Generated by Django 3.1.6 on 2021-03-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210303_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('muzika', 'muzika'), ('film', 'film'), ('izložba', 'izložba'), ('ples', 'ples'), ('poezija', 'poezija')], default='muzika', max_length=10),
        ),
    ]
