export const testData = [
  {
    userName: 'Ivan Jovanović',
    userImgUrl: 'https://randomuser.me/api/portraits/men/36.jpg',
    day: 1,
    time: 1,
    location: 1,
    eventName: 'Kad jaganjci utihnu',
    eventImageUrl: 'https://picsum.photos/id/100/400/300',
    eventCategory: 'Film',
    eventDescription:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  },
  {
    userName: 'Dejan Radošević',
    userImgUrl: 'https://randomuser.me/api/portraits/men/35.jpg',
    day: 1,
    time: 2,
    location: 1,
    eventName: 'Kad su cvetale tikve',
    eventImageUrl: 'https://picsum.photos/id/125/400/300',
    eventCategory: 'Pozorište',
    eventDescription:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  },
  {
    userName: 'Benjamin Dobrdžić',
    userImgUrl: 'https://randomuser.me/api/portraits/men/20.jpg',
    day: 1,
    time: 3,
    location: 1,
    eventName: 'Letu štuke',
    eventImageUrl: 'https://picsum.photos/id/130/400/300',
    eventCategory: 'Muzika',
    eventDescription:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  },
  {
    userName: 'Dejan Babić',
    userImgUrl: 'https://randomuser.me/api/portraits/men/26.jpg',
    day: 1,
    time: 1,
    location: 2,
    eventName: 'Batman',
    eventImageUrl: 'https://picsum.photos/id/450/400/300',
    eventCategory: 'Film',
    eventDescription:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  },
  {
    userName: 'Blerdijan Koliqi',
    userImgUrl: 'https://randomuser.me/api/portraits/men/14.jpg',
    day: 1,
    time: 2,
    location: 2,
    eventName: 'Perper',
    eventImageUrl: 'https://picsum.photos/id/101/400/300',
    eventCategory: 'Muzika',
    eventDescription:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  },
  {
    userName: 'Marko Marković',
    userImgUrl: 'https://randomuser.me/api/portraits/men/36.jpg',
    day: 1,
    time: 3,
    location: 1,
    eventName: 'Kad jaganjci utihnu',
    eventImageUrl: 'https://picsum.photos/id/100/400/300',
    eventCategory: 'Film',
    eventDescription:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  },
  {
    userName: 'Marko Marković',
    userImgUrl: 'https://randomuser.me/api/portraits/men/36.jpg',
    day: 1,
    time: 1,
    location: 3,
    eventName: 'Kad jaganjci utihnu',
    eventImageUrl: 'https://picsum.photos/id/100/400/300',
    eventCategory: 'Film',
    eventDescription:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  },
  {
    userName: 'Ivan Jovanović',
    userImgUrl: 'https://randomuser.me/api/portraits/men/36.jpg',
    day: 2,
    time: 1,
    location: 1,
    eventName: 'Kad jaganjci utihnu',
    eventImageUrl: 'https://picsum.photos/id/100/400/300',
    eventCategory: 'Film',
    eventDescription:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  },
  {
    userName: 'Benjamin Dobrdžić',
    userImgUrl: 'https://randomuser.me/api/portraits/men/20.jpg',
    day: 2,
    time: 3,
    location: 1,
    eventName: 'Letu štuke',
    eventImageUrl: 'https://picsum.photos/id/130/400/300',
    eventCategory: 'Muzika',
    eventDescription:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  },
  {
    userName: 'Dejan Babić',
    userImgUrl: 'https://randomuser.me/api/portraits/men/26.jpg',
    day: 2,
    time: 1,
    location: 2,
    eventName: 'Batman',
    eventImageUrl: 'https://picsum.photos/id/450/400/300',
    eventCategory: 'Film',
    eventDescription:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  },
  {
    userName: 'Blerdijan Koliqi',
    userImgUrl: 'https://randomuser.me/api/portraits/men/14.jpg',
    day: 2,
    time: 2,
    location: 2,
    eventName: 'Perper',
    eventImageUrl: 'https://picsum.photos/id/101/400/300',
    eventCategory: 'Muzika',
    eventDescription:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  },
  {
    userName: 'Marko Marković',
    userImgUrl: 'https://randomuser.me/api/portraits/men/36.jpg',
    day: 2,
    time: 3,
    location: 1,
    eventName: 'Kad jaganjci utihnu',
    eventImageUrl: 'https://picsum.photos/id/100/400/300',
    eventCategory: 'Film',
    eventDescription:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  },
];
